In [1]:
import pandas as pd
import regex as re
import sqlalchemy as sqla
import numpy as np

In [8]:
details_regex = pd.read_csv('details_cleaned.csv')
details_regex

,BEGIN_DATE,BEGIN_TIME,END_DATE,END_TIME,EPISODE_ID,EVENT_ID,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,...,BEGIN_LOCATION,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE
0,08-JUL-16,17:55:00,08-JUL-16,17:55:00,105872,635287,Thunderstorm Wind,C,105,LOUDON,...,JENA,0.56,W,JENA,35.6500,-84.1800,35.6500,-84.1800,The combination of summer heating and high low...,Numerous trees were reported down in the Green...
1,08-JUL-16,18:10:00,08-JUL-16,18:10:00,105872,635296,Thunderstorm Wind,C,155,SEVIER,...,PITNER,1.32,WSW,PITNER,35.8700,-83.7700,35.8700,-83.7700,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...
2,08-JUL-16,19:10:00,08-JUL-16,19:10:00,105872,635301,Thunderstorm Wind,C,7,BLEDSOE,...,DILL,1.38,S,DILL,35.5600,-85.2000,35.5600,-85.2000,The combination of summer heating and high low...,Several trees were reported down across the so...
3,08-JUL-16,18:40:00,08-JUL-16,18:40:00,105872,635299,Thunderstorm Wind,C,123,MONROE,...,TELLICO PLAINS,0.69,N,TELLICO PLAINS,35.3800,-84.3000,35.3800,-84.3000,The combination of summer heating and high low...,A few trees were reported down one mile north ...
4,14-JUL-16,15:40:00,14-JUL-16,15:40:00,105948,635802,Hail,C,93,KNOX,...,LOVELL,1.32,ENE,LOVELL,35.9100,-84.1300,35.9100,-84.1300,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15459,27-SEP-25,12:00:00,27-SEP-25,14:00:00,207597,1294715,Flash Flood,C,73,HAWKINS,...,COLD SPGS,2.70,E,COLD SPGS,36.5342,-82.8180,36.5219,-82.8130,Numerous showers and thunderstorms developing ...,Social media video showed a small stream out o...
15460,27-SEP-25,10:35:00,27-SEP-25,12:35:00,207597,1294716,Flood,C,155,SEVIER,...,PINE GROVE,1.11,ESE,PINE GROVE,35.8154,-83.5561,35.8114,-83.5559,Numerous showers and thunderstorms developing ...,"Ridge Road, just south of the Sevier County So..."
15461,27-SEP-25,10:53:00,27-SEP-25,12:53:00,207597,1294717,Flood,C,73,HAWKINS,...,COLD SPGS,1.07,SSW,COLD SPGS,36.5009,-82.8654,36.4959,-82.8621,Numerous showers and thunderstorms developing ...,A spotter reported 4 inches of water crossing ...
15462,27-SEP-25,11:45:00,27-SEP-25,13:45:00,207597,1294718,Flood,C,155,SEVIER,...,SEVIERVILLE,1.21,SE,SEVIERVILLE,35.8609,-83.5575,35.8570,-83.5567,Numerous showers and thunderstorms developing ...,Burden Hill Road at Eastgate Road is closed du...
15463,06-SEP-25,04:00:00,06-SEP-25,04:35:00,207573,1294606,Thunderstorm Wind,C,19,CARTER,...,ELIZABETHTON,2.90,E,BULADEEN,36.3538,-82.2033,36.4675,-81.9780,An isolated severe thunderstorm ahead of a col...,A severe thunderstorm produced a swath of inte...

In [12]:
regex_narratives = details_regex[['EPISODE_ID','EVENT_ID','EPISODE_NARRATIVE','EVENT_NARRATIVE']]
regex_narratives

,EPISODE_ID,EVENT_ID,EPISODE_NARRATIVE,EVENT_NARRATIVE
0,105872,635287,The combination of summer heating and high low...,Numerous trees were reported down in the Green...
1,105872,635296,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...
2,105872,635301,The combination of summer heating and high low...,Several trees were reported down across the so...
3,105872,635299,The combination of summer heating and high low...,A few trees were reported down one mile north ...
4,105948,635802,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.
...,...,...,...,...
15459,207597,1294715,Numerous showers and thunderstorms developing ...,Social media video showed a small stream out o...
15460,207597,1294716,Numerous showers and thunderstorms developing ...,"Ridge Road, just south of the Sevier County So..."
15461,207597,1294717,Numerous showers and thunderstorms developing ...,A spotter reported 4 inches of water crossing ...
15462,207597,1294718,Numerous showers and thunderstorms developing ...,Burden Hill Road at Eastgate Road is closed du...
15463,207573,1294606,An isolated severe thunderstorm ahead of a col...,A severe thunderstorm produced a swath of inte...

In [ ]:
regex_narratives.to_csv()